# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `uuid7` gem.
# Please instead update this file by running `bin/tapioca gem uuid7`.


# UUID v7 Generator
#
# source://uuid7//lib/uuid7.rb#10
module UUID7
  class << self
    # Generate a new UUID v7
    #
    # @api public
    # @example Generate a new UUID v7 for the current timestamp
    #   UUID7.generate
    # @param timestamp [Integer] the timestamp to use for UUID v7
    # @return [String] the generated UUID v7 string
    #
    # source://uuid7//lib/uuid7.rb#20
    def generate(timestamp: T.unsafe(nil)); end
  end
end

# UUIDv7 with millisecond precision layout
#
# 48 bits for unix timestamp with millisecond precision
# 74 bits for random data
#
# @api private
#
# source://uuid7//lib/uuid7/generator.rb#11
module UUID7::Generator
  class << self
    # Instantiates a new layout
    #
    # @api private
    # @example Generate a new UUID v7 layout for the millisecond
    #   UUID::V7.generate(timestamp)
    # @param timestamp [Integer] the timestamp to use for the layout
    # @return [Array<Integer>] the generated UUID v7 layout
    #
    # source://uuid7//lib/uuid7/generator.rb#22
    def generate(timestamp); end
  end
end

# @api private
#
# source://uuid7//lib/uuid7/generator.rb#13
UUID7::Generator::VARIANT_RFC4122 = T.let(T.unsafe(nil), Integer)

# @api private
#
# source://uuid7//lib/uuid7/generator.rb#12
UUID7::Generator::VERSION_7 = T.let(T.unsafe(nil), Integer)

# source://uuid7//lib/uuid7/version.rb#4
UUID7::VERSION = T.let(T.unsafe(nil), String)
