plugins:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.1

Sorbet/HasSigil:
  Enabled: true
  MinimumStrictness: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
