plugins:
  - rubocop-sorbet

AllCops:
  Enabled: true
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Sorbet/HasSigil:
  Enabled: true
  MinimumStrictness: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
