plugins:
  - rubocop-sorbet

AllCops:
  Enable: true
  TargetRubyVersion: 3.1
  Exclude:
    - 'vendor/**/*'

Sorbet/HasSigil:
  Enabled: true
  MinimumStrictness: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
